### PR TITLE
Fixing cli.common.CLI.__call__ - solves #29

### PR DESCRIPTION
**Pull request by Lucas-C**

### CODE REVIEW

**Comment by stardust85** [comment]
I like your fixing commit, but I have some some small enhancement requests regarding the --version flag. I'll mention them in place. You can either fix them, or revert the 'Adding --version flag' commit and create a separate merge request for the --version change.

**Comment by Lucas-C** [comment]
OK. I removed the extraneous commit and created another PR: https://github.com/stardust85/repositorytools/pull/31

**Comment by stardust85** [comment]
I see the same two commits in PR #31

**Comment by stardust85** [comment]
Thanks for contribution, merged 👍

**Pull request merged**
