### PR TITLE
Resolve remote artifacts more completely

### PR DESCRIPTION
**Pull request by sambrightman**
The resolve method can return a real version when given
e.g. 1.0.0-RELEASE, amongst other items which are currently not
present/updated. I wanted especially this real version and the SHA1
but I guess the other items could be useful too. I've tried to not
resolve anything which is optional by default (see the URL in the
commit message).

### CODE REVIEW

**Comment by sambrightman** [comment]
@stardust85 would it be possible to get a release with this in?

**Comment by stardust85** [comment]
Yes, I'll do it on Monday.

**Comment by sambrightman** [comment]
Bump. Thanks!

**Comment by stardust85** [comment]
released as 4.2.4

**Pull request merged**
